package com.example.openbanking.model;

import jakarta.persistence.*;
import lombok.Data;
import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Represents a financial transaction for a specific bank account.
 * This entity is used to track deposits, withdrawals, and payments.
 */
@Entity
@Data
public class Transaction {

    /**
     * Unique identifier for the transaction.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The IBAN of the account associated with this transaction.
     */
    private String accountIban;

    /**
     * The amount involved in the transaction.
     * Positive values indicate deposits, while negative values indicate withdrawals.
     */
    private BigDecimal amount;

    /**
     * The timestamp when the transaction was recorded.
     */
    private LocalDateTime timestamp;
}